---
version: 2
workers:
- type: router
  realms:
  - name: default
    roles:
    - name: anonymous
      permissions:
      - uri: ""
        match: prefix
        allow: {call: true, publish: true, register: true, subscribe: true}
  transports:
  - type: websocket
    endpoint:
      type: tcp
      interface: localhost
      port: 56666
