# Docker-like setup that serves as a local drop-in for the corresponding Travis services
version: "2"
services:
  test:
    build: .
    user: 1000:1000
    links:
      - crossbar
    volumes:
      - .:/app
    environment:
      CROSSBAR_HOST: crossbar
    entrypoint: dockerize -wait http://crossbar:8080 pytest

  crossbar:
    image: crossbario/crossbar:cpy3-17.5.1
    volumes:
      - ./crossbar-config.yaml:/node/.crossbar/config.yaml:ro
    command: --loglevel trace
