---
version: 2
workers:
- type: router
  realms:
  - name: default
    roles:
    - name: client
      permissions:
      - uri: ""
        match: prefix
        allow: {call: true, publish: false, register: false, subscribe: true}
        disclose: {caller: true}
    - name: server
      permissions:
      - uri: ""
        match: prefix
        allow: {call: true, publish: true, register: true, subscribe: true}
  transports:
  - type: websocket
    endpoint:
      type: tcp
      interface: localhost
      port: 56666
    auth:
      wampcra:
        type: static
        users:
          testserver:
            secret: server123
            role: server
          testclient:
            secret: client123
            role: client
